version: "3.8"
services:
  database:
    container_name: cinetfilx-db
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cinetflix
    ports: 
      - "3306:3306"
    networks:
      - cinetflix-net
  server:
    container_name: cinetflix-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    networks:
      - cinetflix-net
    links: 
      - database
    depends_on: 
      - database
    environment:
      WAIT_HOSTS: database:3306
      WAIT_BEFORE: 180
      WAIT_SLEEP_INTERVAL: 60

networks:
  cinetflix-net: